import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
const origin = 'http://127.0.0.1:4181';
const server = spawn(process.execPath, ['examples/server.mjs'], { stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true, env: { ...process.env, SITEWALL_DEMO_PORT: '4181' } });
let logs = '', browser, release;
server.stdout.on('data', data => { logs += data; }); server.stderr.on('data', data => { logs += data; });
try {
  for (let i = 0; i < 100 && !logs.includes('SiteWall example:'); i++) { if (server.exitCode !== null) throw new Error(logs); await delay(100); }
  browser = await chromium.launch({ headless: true, channel: process.env.SITEWALL_BROWSER_CHANNEL || (process.platform === 'win32' ? 'chrome' : undefined) });
  const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  let requestInfo, executions = 0, holdNext = false;
  await page.route('**/__sitewall/prompts', async route => {
    if (route.request().method() !== 'POST') return route.continue();
    executions++;
    requestInfo = { body: route.request().postDataJSON(), headers: route.request().headers() };
    if (executions === 1 || holdNext) { holdNext = false; await new Promise(resolve => { release = resolve; }); }
    await route.fulfill({ json: { status: 'completed', exitCode: 0, output: 'Simulated result' } });
  });
  await page.goto(origin + '/sitewall');
  await page.waitForFunction(() => window.sitewall?.events().filter(e => e.type === 'ready').length >= 5);
  await page.getByRole('button', { name: 'Prompt Agent' }).click();
  const editor = page.getByRole('textbox', { name: 'Instruction for Agent' });
  await page.getByRole('button', { name: 'Creative', exact: true }).click();
  await editor.fill('Start implementing'); await editor.press('Enter');
  await expect.poll(() => executions).toBe(1);
  expect(requestInfo.body.instruction).toBe('.creative Start implementing');
  await editor.fill('Keep the existing colors'); await editor.press('Enter');
  await expect(page.getByText('You · Queued', { exact: true })).toBeVisible();
  expect(executions).toBe(1);
  const relay = async (method, args = []) => {
    const response = await fetch(origin + '/__sitewall/session', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-SiteWall-Token': requestInfo.headers['x-sitewall-token'] }, body: JSON.stringify({ sessionId: requestInfo.body.sessionId, method, args }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error); return data.result;
  };
  const inputs = await relay('agent.takeOwnerInput');
  expect(inputs.map(item => item.instruction)).toEqual(['.creative Keep the existing colors']);
  await relay('agent.acknowledge', [inputs[0].id, 'Keeping the existing colors']);
  await expect(page.getByText('You · Incorporated', { exact: true })).toBeVisible();
  await relay('agent.requestInteraction', [{ id: 'implementation', type: 'implementation-approval', title: 'Update header', summary: 'Replace the header layout', changes: ['Keep existing colors'] }]);
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.screenshot({ path: '.demo/agent-interaction.png' });
  await page.getByRole('button', { name: 'Close interaction', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await editor.fill('One more thought while deciding'); await editor.press('Enter');
  const extra = (await relay('agent.takeOwnerInput'))[0]; expect(extra.instruction).toBe('.creative One more thought while deciding');
  await relay('agent.acknowledge', [extra.id]);
  await page.getByRole('button', { name: 'Respond', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('status').filter({ hasText: 'Waiting for you' })).toHaveCount(1);
  await page.getByRole('button', { name: 'Reject', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeDisabled();
  await page.getByRole('textbox', { name: 'What should happen next?' }).fill('Keep the layout too');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const responses = await relay('agent.takeOwnerInput');
  expect(responses[0].response).toMatchObject({ action: 'reject', text: 'Keep the layout too' });
  await relay('agent.acknowledge', [responses[0].id]);
  await relay('agent.reportInteraction', ['implementation', { success: true, summary: 'Keeping both layout and colors' }]);
  await relay('agent.requestInteraction', [{ id: 'variants', type: 'variants', title: 'Choose a direction', summary: 'Select one', choices: [{ id: 'A', title: 'Direction A' }, { id: 'B', title: 'Direction B' }, { id: 'C', title: 'Direction C' }] }]);
  await page.getByRole('radio', { name: 'Direction A' }).check();
  await page.getByRole('radio', { name: 'Direction B' }).check();
  await expect(page.getByRole('radio', { name: 'Direction A' })).not.toBeChecked();
  await page.getByRole('button', { name: 'OK', exact: true }).click();
  const choice = (await relay('agent.takeOwnerInput'))[0]; expect(choice.response.selected).toEqual(['B']);
  await relay('agent.acknowledge', [choice.id]); await relay('agent.reportInteraction', ['variants', { success: true, summary: 'Selected B' }]);
  await relay('agent.requestInteraction', [{ id: 'turn', type: 'owner-turn', title: 'Anything to add?', summary: 'Optional input', deadline: Date.now() + 900, allowPass: true }]);
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Close interaction', exact: true }).click();
  await expect.poll(() => page.evaluate(() => window.sitewall.agent.snapshot().interactions.find(item => item.card.id === 'turn').state)).toBe('submitted');
  const pass = (await relay('agent.takeOwnerInput'))[0]; expect(pass.response.action).toBe('pass');
  await relay('agent.acknowledge', [pass.id]); await relay('agent.reportInteraction', ['turn', { success: true, summary: 'Passed' }]);
  await page.getByRole('button', { name: 'Express', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Creative', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await expect(page.getByRole('button', { name: 'Express', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const off = (await relay('agent.takeOwnerInput'))[0]; expect(off.instruction).toBe('.creative off');
  await relay('agent.acknowledge', [off.id]);
  release();
  await expect(page.getByRole('button', { name: 'Stop', exact: true })).toBeDisabled();
  await relay('agent.requestInteraction', [{ id: 'clarify', type: 'clarification', title: 'Which tone?', summary: 'Choose or describe', choices: [{ id: 'calm', title: 'Calm' }, { id: 'bold', title: 'Bold' }], allowText: true }]);
  await page.getByRole('radio', { name: 'Calm' }).check();
  await page.getByRole('textbox', { name: 'Your answer' }).fill('Calm, with strong headings');
  await page.getByRole('button', { name: 'Send answer' }).click();
  await expect(page.getByRole('button', { name: 'Stop', exact: true })).toBeDisabled();
  const answer = (await relay('agent.takeOwnerInput'))[0]; expect(answer.response).toMatchObject({ action: 'answer', selected: ['calm'], text: 'Calm, with strong headings' });
  await relay('agent.acknowledge', [answer.id]); await relay('agent.reportInteraction', ['clarify', { success: true, summary: 'Tone clarified' }]);
  await relay('agent.requestInteraction', [{ id: 'proposal', type: 'proposal', title: 'Proposed direction', summary: 'Use calm typography', implications: ['Preserve navigation'], artifacts: [{ title: 'Preview', kind: 'preview', url: '/' }] }]);
  await expect(page.getByRole('link', { name: 'Preview', exact: true })).toHaveAttribute('href', '/');
  await page.getByRole('button', { name: 'Revise', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeDisabled();
  await page.getByRole('textbox', { name: 'What would you like revised?' }).fill('Use larger headings');
  await page.getByRole('button', { name: 'Send', exact: true }).click();
  const revision = (await relay('agent.takeOwnerInput'))[0]; expect(revision.response).toMatchObject({ action: 'revise', text: 'Use larger headings' });
  await relay('agent.acknowledge', [revision.id]); await relay('agent.reportInteraction', ['proposal', { success: true, summary: 'Proposal revised' }]);
  await relay('agent.requestInteraction', [{ id: 'review', type: 'review', title: 'Review result', summary: 'Heading update ready', canRevert: true, metadata: { branch: 'agent-owned-test-branch' } }]);
  await expect(page.getByRole('button', { name: 'Revert', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Accept', exact: true }).click();
  const accept = (await relay('agent.takeOwnerInput'))[0]; expect(accept.response.action).toBe('accept');
  await relay('agent.acknowledge', [accept.id]);
  expect((await relay('agent.snapshot')).interactions.at(-1).state).toBe('submitted');
  await relay('agent.reportInteraction', ['review', { success: false, summary: 'Merge conflict; no merge performed' }]);
  await expect(page.getByText('Merge conflict; no merge performed', { exact: true })).toBeVisible();
  await relay('agent.requestInteraction', [{ id: 'many', type: 'variants', title: 'Combine directions', summary: 'Choose several', selection: 'many', choices: [{ id: 'A', title: 'Combine A' }, { id: 'B', title: 'Combine B' }] }]);
  await page.getByRole('checkbox', { name: 'Combine A' }).check(); await page.getByRole('checkbox', { name: 'Combine B' }).check();
  await page.getByRole('button', { name: 'OK', exact: true }).click();
  const many = (await relay('agent.takeOwnerInput'))[0]; expect(many.response.selected).toEqual(['A', 'B']);
  await relay('agent.acknowledge', [many.id]); await relay('agent.reportInteraction', ['many', { success: true, summary: 'Combining A and B' }]);
  await page.evaluate(async () => { await window.sitewall.focus('home'); await window.sitewall.selectElement('h1'); window.sitewall.configure({ zoom: .77 }); });
  await editor.fill('UNSENT_PRIVATE_PROMPT');
  await page.reload();
  await page.waitForFunction(() => !!window.sitewall);
  expect(await page.evaluate(() => window.sitewall.agent.snapshot())).toEqual({ inputs: [], interactions: [], status: 'Idle' });
  expect(await page.evaluate(() => window.sitewall.inspectSelection())).toBeNull();
  expect(await page.evaluate(() => window.sitewall.getState().zoom)).toBe(.77);
  expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toMatch(/UNSENT_PRIVATE_PROMPT|Keep the existing colors|Start implementing/);
  await page.getByRole('button', { name: 'Prompt Agent' }).click();
  await expect(page.locator('.sw-agent-prompt .cm-placeholder')).toBeVisible();
  await expect(page.locator('.sw-agent-history')).toHaveText('');
  await page.getByRole('textbox', { name: 'Instruction for Agent' }).fill('Clear this draft');
  await page.evaluate(() => window.sitewall.agent.enqueue('Clear this queued thought'));
  await page.getByRole('button', { name: 'New Session', exact: true }).click();
  await expect(page.locator('.sw-agent-prompt .cm-placeholder')).toBeVisible();
  await expect(page.locator('.sw-agent-history')).toHaveText('');
  holdNext = true;
  const beforeBoundary = executions;
  await editor.fill('Work until a boundary'); await editor.press('Enter');
  await expect.poll(() => executions).toBe(beforeBoundary + 1);
  await editor.fill('Follow up at the boundary'); await editor.press('Enter');
  release();
  await expect.poll(() => executions).toBe(beforeBoundary + 2);
  await expect(page.getByRole('button', { name: 'Stop', exact: true })).toBeDisabled();
  expect(requestInfo.body.instruction).toContain('Queued owner input is ready');
  expect(await page.locator('.sw-agent-history').textContent()).not.toContain('agent.takeOwnerInput');
  const boundaryInput = (await relay('agent.takeOwnerInput'))[0]; expect(boundaryInput.instruction).toBe('Follow up at the boundary');
  await relay('agent.acknowledge', [boundaryInput.id]);
  holdNext = true;
  const beforeStop = executions;
  await editor.fill('Work until stopped'); await editor.press('Enter');
  await expect.poll(() => executions).toBe(beforeStop + 1);
  await editor.fill('Do not run this after Stop'); await editor.press('Enter');
  await page.getByRole('button', { name: 'Stop', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Stop', exact: true })).toBeDisabled();
  release(); await delay(300);
  expect(executions).toBe(beforeStop + 1);
  expect((await page.evaluate(() => window.sitewall.agent.snapshot())).inputs.at(-1).state).toBe('queued');
  await page.getByRole('button', { name: 'New Session', exact: true }).click();
  await expect(page.locator('.sw-agent-history')).toHaveText('');
  await page.screenshot({ path: '.demo/agent-panel.png' });
  expect(errors).toEqual([]);
  console.log('PASS: authenticated cards, running interjections, acknowledgement, mandatory followup, variants, timeout/pass, mutex modes and ephemeral reload');
} finally { release?.(); await browser?.close(); server.kill(); }
