import { chromium, expect } from '@playwright/test';
import { verifyFeatures } from './browser-features.mjs';
import { spawn } from 'node:child_process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { setTimeout as delay } from 'node:timers/promises';
const original = await readFile(new URL('../examples/app.css', import.meta.url), 'utf8');
const server = spawn(process.execPath, ['examples/server.mjs'], { stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true, env: { ...process.env, SITEWALL_DEMO_PORT: '4174' } });
let logs = '';
server.stdout.on('data', data => { logs += data; });
server.stderr.on('data', data => { logs += data; });
let browser;
try {
  await mkdir(new URL('../.artifacts/', import.meta.url), { recursive: true });
  for (let i = 0; i < 100 && !logs.includes('SiteWall example:'); i++) { if (server.exitCode !== null) throw new Error(logs); await delay(100); }
  if (!logs.includes('SiteWall example:')) throw new Error('Example server timeout: ' + logs);
  browser = await chromium.launch({ headless: true, channel: process.env.SITEWALL_BROWSER_CHANNEL || (process.platform === 'win32' ? 'chrome' : undefined) });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('http://127.0.0.1:4174/sitewall');
  await page.waitForFunction(() => window.sitewall && window.sitewall.events().filter(e => e.type === 'ready').length >= 5);
  const api = (method, ...args) => page.evaluate(async ([method, args]) => window.sitewall[method](...args), [method, args]);
  const route = id => page.frameLocator(`iframe[title="${id}"]`);
  // A focus-selection click must not activate the application below it.
  await page.getByRole('button', { name: 'Focus Shop', exact: true }).click();
  await expect(route('Shop').getByTestId('cart')).toHaveText('0');
  await api('click', '[data-testid="add"]');
  await expect(route('Home').getByTestId('cart')).toHaveText('1');
  await api('focus', 'home');
  await api('click', '[data-testid="browse"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('shop');
  await expect.poll(async () => (await api('inspect', 'home')).route).toBe('/');
  await api('focus', 'home');
  await api('click', '[data-testid="add-and-browse"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('shop');
  await expect(route('Shop').getByTestId('cart')).toHaveText('2');
  await api('navigate', '/login');
  await api('type', 'input[name="username"]', 'Alex');
  await api('click', '[data-testid="login"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('account');
  await expect(route('Home').getByTestId('user')).toHaveText('Alex');
  await expect.poll(async () => (await api('inspect', 'login')).route).toBe('/login');
  await api('click', '[data-testid="logout"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('login');
  await expect(route('Shop').getByTestId('user')).toHaveText('Guest');
  await api('navigate', '/checkout');
  await api('click', 'main button');
  await expect.poll(async () => (await api('getState')).focused).toBe('thanks');
  await expect.poll(async () => (await api('inspect', 'checkout')).route).toBe('/checkout');
  await expect(route('Home').getByTestId('cart')).toHaveText('0');
  await api('navigate', '/redirect');
  await expect.poll(async () => (await api('getState')).focused).toBe('shop');
  await expect(page.locator('.sw-blocked')).toContainText('redirects');
  expect((await api('inspect', 'redirect')).available).toBe(false);
  await api('show', 'redirect', false);
  // Concurrent agent navigation is serialized; the last requested destination wins.
  await page.evaluate(() => Promise.all([window.sitewall.navigate('/'), window.sitewall.navigate('/shop')]));
  expect((await api('getState')).focused).toBe('shop');
  await api('configure', { viewport: { width: 820, height: 900 }, zoom: .3, pan: { x: 10, y: 10 }, columns: 3 });
  expect((await api('inspect', 'home')).viewport).toEqual({ width: 820, height: 900 });
  expect(await page.locator('iframe[title="Home"]').evaluate(frame => ({
    iframe: frame.offsetWidth,
    body: frame.parentElement.clientWidth,
    panel: frame.closest('.sw-page').clientWidth,
  }))).toEqual({ iframe: 820, body: 820, panel: 820 });
  await api('navigate', '/story');
  await api('scroll', 0, 500);
  const images = await api('capture', 'story');
  expect(images.length).toBeGreaterThan(2);
  expect((await api('inspect', 'story')).viewport.height).toBe(900);
  expect((await api('inspect', 'story')).scroll.y).toBe(500);
  await api('show', 'story', false);
  await api('show', 'story', true);
  expect((await api('inspect', 'story')).scroll.y).toBe(500);
  // Applying source CSS inline must retain the original external sheet's URL base.
  await page.route('**/fixtures/styles/app.css', request => request.fulfill({ contentType: 'text/css', body: original }));
  await page.route('**/fixtures/assets/pixel.svg', request => request.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"><path fill="red" d="M0 0h1v1H0z"/></svg>' }));
  await route('Home').locator('body').evaluate(async body => {
    const link = document.querySelector('link[href="/app.css"]');
    await new Promise((resolve, reject) => { link.onload = resolve; link.onerror = reject; link.href = '/fixtures/styles/app.css'; });
    const probe = document.createElement('div'); probe.className = 'relative-probe'; body.append(probe);
  });
  await api('focus', 'home');
  await api('clearSelection');
  await expect(page.locator('.sw-style-rule[data-rule-index="11"]')).toBeVisible();
  await expect(page.locator('.sw-style-rule[data-rule-index="8"]')).toHaveCount(0);
  await api('selectElement', 'h1', 'home');
  const ruleCard = page.locator('.sw-style-rule[data-rule-index="2"]');
  const editor = ruleCard.getByLabel('CSS rule content');
  const editorText = () => editor.evaluate(el => [...el.querySelectorAll('.cm-line')].map(line => line.textContent).join('\n'));
  await expect(editor).toBeVisible();
  await expect.poll(editorText).toContain('font-size: 37px');
  await expect(page.locator('.cm-lineNumbers')).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Format CSS', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Reopen from disk', exact: true })).toHaveCount(0);
  await expect(page.locator('.sw-styles')).not.toContainText('APPLICATION STYLES');
  await expect(page.locator('.sw-style-rule[data-rule-index="8"]')).toHaveCount(0);
  await expect(page.locator('.sw-style-rule[data-rule-index="11"]')).toHaveCount(0);
  await expect(ruleCard.locator('.sw-rule-filename')).toHaveText('examples/app.css');
  await page.getByLabel('Filter styles').fill('does-not-match');
  await expect(editor).toBeHidden();
  await api('filterStyles', 'font-size');
  await expect(page.getByLabel('Filter styles')).toHaveValue('font-size');
  await expect(editor).toBeVisible();
  await api('filterStyles', 'app.css');
  await editor.fill('h1 { padd');
  await editor.press('Control+Space');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('padding');
  await editor.press('Escape');
  await editor.fill('h1 { color: r');
  await editor.press('Control+Space');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('red');
  await editor.press('Escape');
  await editor.fill('h1 { padding: 12px; }');
  await editor.press('Control+Home');
  for (let i = 0; i < 14; i++) await editor.press('ArrowRight');
  await editor.press('ArrowUp');
  await expect.poll(editorText).toBe('h1 { padding: 13px; }');
  await editor.press('Control+Shift+f');
  await expect.poll(editorText).toBe('h1 {\n  padding: 13px;\n}');
  const originalRule = /h1 \{[^}]+\}/.exec(original)[0];
  const editedRule = originalRule.replace('color: #135649;', 'color: rgb(201, 20, 70);');
  await editor.fill(editedRule);
  await page.getByLabel('Toggle styles').click();
  await page.getByLabel('Toggle styles').click();
  const edited = original.replace(originalRule, editedRule);
  await expect.poll(() => page.evaluate(async () => (await window.sitewall.styles.read('examples/app.css')).content)).toBe(edited);
  expect(await readFile(new URL('../examples/app.css', import.meta.url), 'utf8')).toBe(edited);
  await expect.poll(() => route('Home').locator('h1').evaluate(el => getComputedStyle(el).color)).toBe('rgb(201, 20, 70)');
  await expect.poll(() => route('Shop').locator('h1').evaluate(el => getComputedStyle(el).color)).toBe('rgb(201, 20, 70)');
  const modified = edited + '\n.relative-probe{background-image:url(../assets/pixel.svg)}\n';
  await page.evaluate(async content => {
    const file = await window.sitewall.styles.read('examples/app.css');
    await window.sitewall.styles.save({ ...file, content });
  }, modified);
  await expect.poll(() => route('Home').locator('.relative-probe').evaluate(el => getComputedStyle(el).backgroundImage)).toBe('url("http://127.0.0.1:4174/fixtures/assets/pixel.svg")');
  await route('Home').locator('.relative-probe').evaluate(el => el.remove());
  await route('Home').locator('body').evaluate(body => {
    const probe = document.createElement('div'); probe.id = 'cascade-probe'; probe.className = 'probe'; probe.style.opacity = '.7'; body.append(probe);
    const style = document.createElement('style'); style.dataset.cascadeTest = 'true';
    style.textContent = '@layer first, second; @layer first { #cascade-probe { margin-top: 10px; padding-top: 10px !important; } } @layer second { #cascade-probe { margin-top: 20px; padding-top: 20px !important; } } .probe { color: red !important; opacity: .3; } #cascade-probe { color: blue; border-top-width: 1px; &.probe { border-top-width: 2px; } } @media(min-width:99999px) { #cascade-probe { color: purple !important; } }';
    document.head.append(style);
  });
  const cascade = await api('inspectStyles', 'home', '#cascade-probe');
  const property = name => cascade.cascade.find(entry => entry.property === name);
  expect(property('color').computed).toBe('rgb(255, 0, 0)');
  expect(property('color').declarations[0].important).toBe(true);
  expect(property('margin-top').declarations[0].layer).toBe('second');
  expect(property('padding-top').declarations[0].layer).toBe('first');
  expect(property('opacity').declarations[0].inline).toBe(true);
  expect(property('border-top-width').declarations[0].value).toBe('2px');
  await route('Home').locator('body').evaluate(() => { document.querySelector('#cascade-probe')?.remove(); document.querySelector('[data-cascade-test]')?.remove(); });
  await api('configure', { layout: 'overview' });
  await expect(page.getByRole('button', { name: 'Capturing\u2026' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Refresh full pages' })).toBeEnabled({ timeout: 60000 });
  await expect(page.locator('.sw-slices img').first()).toBeVisible();
  await page.screenshot({ path: new URL('../.artifacts/overview.png', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1') });
  const beforeImage = await page.locator('.sw-slices img').first().getAttribute('src');
  const agentEdit = modified + '\nh1{color:rgb(20, 60, 160)}\n';
  await page.evaluate(async content => {
    const file = await window.sitewall.styles.read('examples/app.css');
    await window.sitewall.styles.save({ ...file, content });
  }, agentEdit);
  const strongest = page.locator('.sw-style-rule').first().getByLabel('CSS rule content');
  await expect.poll(() => strongest.innerText()).toContain('h1{color:rgb(20, 60, 160)}');
  await expect.poll(() => page.locator('.sw-slices img').first().getAttribute('src').catch(() => null), { timeout: 20000 }).not.toBe(beforeImage);
  await expect(page.getByRole('button', { name: 'Refresh full pages' })).toBeEnabled({ timeout: 60000 });
  await page.getByRole('button', { name: 'Focus Home', exact: true }).click();
  expect((await api('getState')).layout).toBe('viewport');
  expect((await api('inspect', 'story')).scroll.y).toBe(500);
  await api('configure', { viewport: { width: 430, height: 932 }, zoom: .65, columns: 3, pan: { x: 24, y: 24 } });
  await api('focus', 'home');
  await verifyFeatures(page, api, route);
  await mkdir(new URL('../.artifacts/', import.meta.url), { recursive: true });
  await page.screenshot({ path: new URL('../.artifacts/sitewall.png', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'), fullPage: true });
  expect(errors).toEqual([]);
  const events = await api('events');
  expect(events.some(e => e.type === 'restoration')).toBe(true);
  expect(events.some(e => e.type === 'shared-state')).toBe(true);
  expect(events.some(e => e.type === 'stylesheet')).toBe(true);
  expect(events.some(e => e.type === 'panel-blocked')).toBe(true);
  const disabledPage = await browser.newPage();
  await disabledPage.goto('http://127.0.0.1:4174/');
  expect(await disabledPage.evaluate(() => window.sitewall)).toBeUndefined();
  await disabledPage.goto('http://127.0.0.1:4174/disabled');
  await expect(disabledPage.locator('.sw-root')).toHaveCount(0);
  expect(await disabledPage.evaluate(() => window.sitewall)).toBeUndefined();
  console.log('Browser verification passed: existing navigation/state/capture flows; smooth pointer zoom including native iframe wheel; auto-centering; individual applicable rule editors/filtering/CSS completion/numeric editing/autosave/relative URLs/cascade; element/region selection; prompt context/submission and same-session relay.');
} finally {
  await browser?.close();
  server.kill();
  await writeFile(new URL('../examples/app.css', import.meta.url), original);
}
