import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { setTimeout as delay } from 'node:timers/promises';
const original = await readFile(new URL('../examples/app.css', import.meta.url), 'utf8');
const server = spawn(process.execPath, ['examples/server.mjs'], { stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true, env: { ...process.env, SITEWALL_DEMO_PORT: '4174' } });
let logs = '';
server.stdout.on('data', data => { logs += data; });
server.stderr.on('data', data => { logs += data; });
let browser;
try {
  await mkdir(new URL('../.artifacts/', import.meta.url), { recursive: true });
  for (let i = 0; i < 100 && !logs.includes('SiteWall example:'); i++) { if (server.exitCode !== null) throw new Error(logs); await delay(100); }
  if (!logs.includes('SiteWall example:')) throw new Error('Example server timeout: ' + logs);
  browser = await chromium.launch({ headless: true, channel: process.env.SITEWALL_BROWSER_CHANNEL || (process.platform === 'win32' ? 'chrome' : undefined) });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('http://127.0.0.1:4174/sitewall');
  await page.waitForFunction(() => window.sitewall && window.sitewall.events().filter(e => e.type === 'ready').length >= 5);
  const api = (method, ...args) => page.evaluate(async ([method, args]) => window.sitewall[method](...args), [method, args]);
  const route = id => page.frameLocator(`iframe[title="${id}"]`);
  // A focus-selection click must not activate the application below it.
  await page.getByRole('button', { name: 'Focus Shop', exact: true }).click();
  await expect(route('Shop').getByTestId('cart')).toHaveText('0');
  await api('click', '[data-testid="add"]');
  await expect(route('Home').getByTestId('cart')).toHaveText('1');
  await api('focus', 'home');
  await api('click', '[data-testid="browse"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('shop');
  await expect.poll(async () => (await api('inspect', 'home')).route).toBe('/');
  await api('focus', 'home');
  await api('click', '[data-testid="add-and-browse"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('shop');
  await expect(route('Shop').getByTestId('cart')).toHaveText('2');
  await api('navigate', '/login');
  await api('type', 'input[name="username"]', 'Alex');
  await api('click', '[data-testid="login"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('account');
  await expect(route('Home').getByTestId('user')).toHaveText('Alex');
  await expect.poll(async () => (await api('inspect', 'login')).route).toBe('/login');
  await api('click', '[data-testid="logout"]');
  await expect.poll(async () => (await api('getState')).focused).toBe('login');
  await expect(route('Shop').getByTestId('user')).toHaveText('Guest');
  await api('navigate', '/checkout');
  await api('click', 'main button');
  await expect.poll(async () => (await api('getState')).focused).toBe('thanks');
  await expect.poll(async () => (await api('inspect', 'checkout')).route).toBe('/checkout');
  await expect(route('Home').getByTestId('cart')).toHaveText('0');
  await api('navigate', '/redirect');
  await expect.poll(async () => (await api('getState')).focused).toBe('shop');
  await expect(page.locator('.sw-blocked')).toContainText('redirects');
  expect((await api('inspect', 'redirect')).available).toBe(false);
  await api('show', 'redirect', false);
  // Concurrent agent navigation is serialized; the last requested destination wins.
  await page.evaluate(() => Promise.all([window.sitewall.navigate('/'), window.sitewall.navigate('/shop')]));
  expect((await api('getState')).focused).toBe('shop');
  await api('configure', { viewport: { width: 820, height: 900 }, zoom: .3, pan: { x: 10, y: 10 }, columns: 3 });
  expect((await api('inspect', 'home')).viewport).toEqual({ width: 820, height: 900 });
  await api('navigate', '/story');
  await api('scroll', 0, 500);
  const images = await api('capture', 'story');
  expect(images.length).toBeGreaterThan(2);
  expect((await api('inspect', 'story')).viewport.height).toBe(900);
  expect((await api('inspect', 'story')).scroll.y).toBe(500);
  await api('show', 'story', false);
  await api('show', 'story', true);
  expect((await api('inspect', 'story')).scroll.y).toBe(500);
  await page.getByLabel('Stylesheet', { exact: true }).selectOption('examples/app.css');
  await expect(page.getByLabel('Stylesheet content')).toHaveValue(original);
  const modified = original + '\nh1{color:rgb(201, 20, 70)}\n';
  await page.getByLabel('Stylesheet content').fill(modified);
  await page.getByLabel('Toggle styles').click();
  await page.getByLabel('Toggle styles').click();
  await expect(page.getByLabel('Stylesheet content')).toHaveValue(modified);
  await expect(page.getByRole('status')).toHaveText('Saved');
  expect(await readFile(new URL('../examples/app.css', import.meta.url), 'utf8')).toBe(modified);
  await expect.poll(() => route('Home').locator('h1').evaluate(el => getComputedStyle(el).color)).toBe('rgb(201, 20, 70)');
  await expect.poll(() => route('Shop').locator('h1').evaluate(el => getComputedStyle(el).color)).toBe('rgb(201, 20, 70)');
  await api('configure', { layout: 'overview' });
  await expect(page.getByRole('button', { name: 'Capturing…' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Refresh full pages' })).toBeEnabled({ timeout: 60000 });
  await expect(page.locator('.sw-slices img').first()).toBeVisible();
  await page.screenshot({ path: new URL('../.artifacts/overview.png', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1') });
  const beforeImage = await page.locator('.sw-slices img').first().getAttribute('src');
  const agentEdit = modified + '\nh1{color:rgb(20, 60, 160)}\n';
  await page.evaluate(async content => {
    const file = await window.sitewall.styles.read('examples/app.css');
    await window.sitewall.styles.save({ ...file, content });
  }, agentEdit);
  await expect(page.getByLabel('Stylesheet content')).toHaveValue(agentEdit);
  await expect.poll(() => page.locator('.sw-slices img').first().getAttribute('src').catch(() => null), { timeout: 20000 }).not.toBe(beforeImage);
  await expect(page.getByRole('button', { name: 'Refresh full pages' })).toBeEnabled({ timeout: 60000 });
  await page.getByRole('button', { name: 'Focus Home', exact: true }).click();
  expect((await api('getState')).layout).toBe('viewport');
  expect((await api('inspect', 'story')).scroll.y).toBe(500);
  await api('configure', { viewport: { width: 390, height: 844 }, zoom: .65, columns: 3, pan: { x: 24, y: 24 } });
  await api('focus', 'home');
  await mkdir(new URL('../.artifacts/', import.meta.url), { recursive: true });
  await page.screenshot({ path: new URL('../.artifacts/sitewall.png', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'), fullPage: true });
  expect(errors).toEqual([]);
  const events = await api('events');
  expect(events.some(e => e.type === 'restoration')).toBe(true);
  expect(events.some(e => e.type === 'shared-state')).toBe(true);
  expect(events.some(e => e.type === 'stylesheet')).toBe(true);
  expect(events.some(e => e.type === 'panel-blocked')).toBe(true);
  const disabledPage = await browser.newPage();
  await disabledPage.goto('http://127.0.0.1:4174/');
  expect(await disabledPage.evaluate(() => window.sitewall)).toBeUndefined();
  await disabledPage.goto('http://127.0.0.1:4174/disabled');
  await expect(disabledPage.locator('.sw-root')).toHaveCount(0);
  expect(await disabledPage.evaluate(() => window.sitewall)).toBeUndefined();
  console.log('Browser verification passed: focus protection, links, programmatic and document navigation, login/logout, cart, viewport semantics, capture/scroll restoration, visibility, stylesheet autosave, shared agent session.');
} finally {
  await browser?.close();
  server.kill();
  await writeFile(new URL('../examples/app.css', import.meta.url), original);
}
